// AUTO-GENERATED by memtrace install — Memtrace Rail discovery hook.
// Routes OpenCode tool calls through `memtrace route`. Defaults to observe
// (no-op) unless MEMTRACE_RAIL=nudge|rail|strict. Remove via 'memtrace uninstall'.
import { execFileSync } from 'node:child_process';

const BIN = "memtrace";

export const MemtraceRail = async ({ project, client, $ }) => ({
  'tool.execute.before': async (input, output) => {
    try {
      const tool = input?.tool;
      if (tool !== 'bash' && tool !== 'grep' && tool !== 'glob') return;
      const attempt = {
        host: 'open-code',
        cwd: output?.args?.cwd || process.cwd(),
        tool: tool === 'bash' ? 'Bash' : tool === 'grep' ? 'Grep' : 'Glob',
        input: output?.args || {},
        session_id: input?.sessionID || 'opencode',
      };
      const out = execFileSync(BIN, ['route', '--json', '-'], {
        input: JSON.stringify(attempt), timeout: 1500, encoding: 'utf8',
      });
      const decision = JSON.parse(out);
      if (decision.action === 'suppress_raw_with_result') {
        throw new Error('[Memtrace Rail] ' + (decision.message || 'Use Memtrace for code discovery.') +
          (decision.result ? '\n' + JSON.stringify(decision.result, null, 2) : ''));
      }
    } catch (e) {
      // Fail open on any router/exec error — never block the agent.
      if (e && String(e.message || '').startsWith('[Memtrace Rail]')) throw e;
    }
  },
});
